@startuml

title Main class diagram of user interface

package colors {
    class Colors {
        +black
        +white
        +red
        +green
        +blue
        +yellow
        +lightblue
        +purple
    }
    class BaseColorGradient {
        +CalculateColor(value)
    }
    class MultiColorGradient {
        +__init__(colorPositions, colors)
        +calculateColor(value)
    }
    class TwoColorGradient {
        +__init__(colorZero, colorOne)
    }
    class BaseColorScheme {
        +editorBackgroundColor()
        +editorLineColor()
        +editorLineAbsoptionColorGradient()
        +editorDefualtDomainColor()
        +editorDomainSignalColorGradient()
    }
    class StandardColorScheme {
        +editorBackgroundColor()
        +editorLineColor()
        +editorLineAbsoptionColorGradient()
        +editorDefualtDomainColor()
        +editorDomainSignalColorGradient()
    }

    BaseColorGradient <|-- MultiColorGradient
    MultiColorGradient <|-- TwoColorGradient
    StandardColorScheme <|-- BaseColorScheme
    StandardColorScheme --> TwoColorGradient
}

package main {
    class MainWindow {
        +__init__()
        +updateViews()
    }
}

package Model {
    class model {
        +{static} emptyDocumentFilename
        +__init__()
        +loadEmptyDocument()
        +load(filename)
        +save(filename)
    }

    class AppConfig {

    }

    model --> AppConfig
}

package viewer2D {
    class Viewer2D {
        --
        +__init__()
        +minimumSizeHint()
        +sizeHint()
        +initilizeGL()
        +paintGL()
        +resizeGL()
        --
        +updateScene()
        +updateViewMatrix()
    }
}

package simulation {
    class runner {
        +run()
    }
}

package operations {
    abstract class operation {
        +run(model)
    }
}

package MenuFileOperations {
    class open
    operation <|-- open

    class new
    operation <|-- new

    class save
    operation <|-- save

    class close
    operation <|-- close
}

package SceneEditOperations {
    class extrude
    operation <|-- extrude

    class AddSpeaker
    operation <|-- AddSpeaker

    class SetListenerPos
    operation <|-- SetListenerPos
}

package SceneOperations {
    class Simulate
    operation <|-- Simulate

    class CreateMovie
    operation <|-- CreateMovie
}

MainWindow --> Viewer2D
MainWindow --> model
Viewer2D --> StandardColorScheme
model --> runner
operation --> model
MainWindow --> operation

@enduml