# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created: Thu May 21 14:45:32 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(848, 631)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.btnExtrude = QtGui.QPushButton(self.centralwidget)
        self.btnExtrude.setObjectName("btnExtrude")
        self.verticalLayout.addWidget(self.btnExtrude)
        self.btnAddSpeaker = QtGui.QPushButton(self.centralwidget)
        self.btnAddSpeaker.setObjectName("btnAddSpeaker")
        self.verticalLayout.addWidget(self.btnAddSpeaker)
        self.btnListenerPosition = QtGui.QPushButton(self.centralwidget)
        self.btnListenerPosition.setObjectName("btnListenerPosition")
        self.verticalLayout.addWidget(self.btnListenerPosition)
        spacerItem = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.btnSimulate = QtGui.QPushButton(self.centralwidget)
        self.btnSimulate.setObjectName("btnSimulate")
        self.verticalLayout.addWidget(self.btnSimulate)
        self.btnCreateMovie = QtGui.QPushButton(self.centralwidget)
        self.btnCreateMovie.setObjectName("btnCreateMovie")
        self.verticalLayout.addWidget(self.btnCreateMovie)
        spacerItem1 = QtGui.QSpacerItem(0, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mainView = Viewer2D(self.centralwidget)
        self.mainView.setObjectName("mainView")
        self.verticalLayout_3.addWidget(self.mainView)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.horizontalScrollBar = QtGui.QScrollBar(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalScrollBar.sizePolicy().hasHeightForWidth())
        self.horizontalScrollBar.setSizePolicy(sizePolicy)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.horizontalLayout_2.addWidget(self.horizontalScrollBar)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pushButton_5 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_4 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_2.addWidget(self.pushButton_6)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_8 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 848, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        self.menuDimension = QtGui.QMenu(self.menuOption)
        self.menuDimension.setObjectName("menuDimension")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuDebug = QtGui.QMenu(self.menubar)
        self.menuDebug.setObjectName("menuDebug")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(MainWindow)
        self.actionSave_as.setEnabled(False)
        self.actionSave_as.setVisible(False)
        self.actionSave_as.setObjectName("actionSave_as")
        self.action = QtGui.QAction(MainWindow)
        self.action.setObjectName("action")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.action2D = QtGui.QAction(MainWindow)
        self.action2D.setCheckable(True)
        self.action2D.setChecked(True)
        self.action2D.setObjectName("action2D")
        self.action3D = QtGui.QAction(MainWindow)
        self.action3D.setCheckable(True)
        self.action3D.setEnabled(False)
        self.action3D.setObjectName("action3D")
        self.actionAdvanced_options = QtGui.QAction(MainWindow)
        self.actionAdvanced_options.setObjectName("actionAdvanced_options")
        self.actionOpenPSTD_help = QtGui.QAction(MainWindow)
        self.actionOpenPSTD_help.setObjectName("actionOpenPSTD_help")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionMove_scene = QtGui.QAction(MainWindow)
        self.actionMove_scene.setCheckable(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/noun_1476.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMove_scene.setIcon(icon)
        self.actionMove_scene.setObjectName("actionMove_scene")
        self.actionView_complete_scene = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/noun_70430_cc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionView_complete_scene.setIcon(icon1)
        self.actionView_complete_scene.setObjectName("actionView_complete_scene")
        self.actionAdd_Domain = QtGui.QAction(MainWindow)
        self.actionAdd_Domain.setCheckable(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/noun_40980_cc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Domain.setIcon(icon2)
        self.actionAdd_Domain.setObjectName("actionAdd_Domain")
        self.actionDebug1 = QtGui.QAction(MainWindow)
        self.actionDebug1.setObjectName("actionDebug1")
        self.actionDebug2 = QtGui.QAction(MainWindow)
        self.actionDebug2.setObjectName("actionDebug2")
        self.actionDebug3 = QtGui.QAction(MainWindow)
        self.actionDebug3.setObjectName("actionDebug3")
        self.actionDebug4 = QtGui.QAction(MainWindow)
        self.actionDebug4.setObjectName("actionDebug4")
        self.actionShow_grid = QtGui.QAction(MainWindow)
        self.actionShow_grid.setCheckable(True)
        self.actionShow_grid.setObjectName("actionShow_grid")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuDimension.addAction(self.action2D)
        self.menuDimension.addAction(self.action3D)
        self.menuOption.addAction(self.menuDimension.menuAction())
        self.menuOption.addAction(self.actionAdvanced_options)
        self.menuHelp.addAction(self.actionOpenPSTD_help)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionMove_scene)
        self.menuView.addAction(self.actionView_complete_scene)
        self.menuView.addAction(self.actionShow_grid)
        self.menuDebug.addAction(self.actionDebug1)
        self.menuDebug.addAction(self.actionDebug2)
        self.menuDebug.addAction(self.actionDebug3)
        self.menuDebug.addAction(self.actionDebug4)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuDebug.menuAction())
        self.toolBar.addAction(self.actionAdd_Domain)
        self.toolBar.addAction(self.actionMove_scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionView_complete_scene)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDebug1)
        self.toolBar.addAction(self.actionDebug2)
        self.toolBar.addAction(self.actionDebug3)
        self.toolBar.addAction(self.actionDebug4)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OpenPSTD", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Operations", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExtrude.setText(QtGui.QApplication.translate("MainWindow", "Extrude", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAddSpeaker.setText(QtGui.QApplication.translate("MainWindow", "Add speaker", None, QtGui.QApplication.UnicodeUTF8))
        self.btnListenerPosition.setText(QtGui.QApplication.translate("MainWindow", "Set listener position", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Run", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSimulate.setText(QtGui.QApplication.translate("MainWindow", "Simulate", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCreateMovie.setText(QtGui.QApplication.translate("MainWindow", "Create movie", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Time line", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("MainWindow", "Grid spacing", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("MainWindow", "Max fequency", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_8.setText(QtGui.QApplication.translate("MainWindow", "Advanced options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuOption.setTitle(QtGui.QApplication.translate("MainWindow", "Options", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDimension.setTitle(QtGui.QApplication.translate("MainWindow", "Dimension", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuDebug.setTitle(QtGui.QApplication.translate("MainWindow", "Debug", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen.setText(QtGui.QApplication.translate("MainWindow", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave.setText(QtGui.QApplication.translate("MainWindow", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSave_as.setText(QtGui.QApplication.translate("MainWindow", "Save as.", None, QtGui.QApplication.UnicodeUTF8))
        self.action.setText(QtGui.QApplication.translate("MainWindow", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClose.setText(QtGui.QApplication.translate("MainWindow", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.action2D.setText(QtGui.QApplication.translate("MainWindow", "2D", None, QtGui.QApplication.UnicodeUTF8))
        self.action3D.setText(QtGui.QApplication.translate("MainWindow", "3D", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdvanced_options.setText(QtGui.QApplication.translate("MainWindow", "Advanced options", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpenPSTD_help.setText(QtGui.QApplication.translate("MainWindow", "OpenPSTD help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_scene.setText(QtGui.QApplication.translate("MainWindow", "Move scene", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMove_scene.setToolTip(QtGui.QApplication.translate("MainWindow", "Move the view", None, QtGui.QApplication.UnicodeUTF8))
        self.actionView_complete_scene.setText(QtGui.QApplication.translate("MainWindow", "View complete scene", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdd_Domain.setText(QtGui.QApplication.translate("MainWindow", "Add Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug1.setText(QtGui.QApplication.translate("MainWindow", "Debug1", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug2.setText(QtGui.QApplication.translate("MainWindow", "Debug2", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug3.setText(QtGui.QApplication.translate("MainWindow", "Debug3", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDebug4.setText(QtGui.QApplication.translate("MainWindow", "Debug4", None, QtGui.QApplication.UnicodeUTF8))
        self.actionShow_grid.setText(QtGui.QApplication.translate("MainWindow", "Show grid", None, QtGui.QApplication.UnicodeUTF8))

from Viewer2D import Viewer2D
